// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(OrtganizaDbContext))]
    [Migration("20251122103909_Se_Agrega_virtuals")]
    partial class Se_Agrega_virtuals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Entities.MiembroProyecto", b =>
                {
                    b.Property<Guid>("MiembroProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Baja")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoRol")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MiembroProyectoId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("UserId");

                    b.ToTable("MiembroProyecto");
                });

            modelBuilder.Entity("Entities.Entities.Proyecto", b =>
                {
                    b.Property<Guid>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProyectoId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Entities.Entities.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Baja")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EstimacionDias")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Vencida")
                        .HasColumnType("bit");

                    b.HasKey("TareaId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("Entities.Entities.TareaColaborador", b =>
                {
                    b.Property<Guid>("TareaColaboradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Baja")
                        .HasColumnType("bit");

                    b.Property<Guid>("TareaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TareaColaboradorId");

                    b.HasIndex("TareaId");

                    b.HasIndex("UserId");

                    b.ToTable("TareaColaborador");
                });

            modelBuilder.Entity("Entities.Entities.TareaSolicitudBaja", b =>
                {
                    b.Property<Guid>("TareaSolicitudBajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TareaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TareaSolicitudBajaId");

                    b.HasIndex("TareaId");

                    b.HasIndex("UserId");

                    b.ToTable("TareaSolicitudBaja");
                });

            modelBuilder.Entity("Entities.Entities.TareaTrace", b =>
                {
                    b.Property<Guid>("TareaTraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EstadoCambiado")
                        .HasColumnType("int");

                    b.Property<Guid>("TareaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TareaTraceId");

                    b.HasIndex("TareaId");

                    b.HasIndex("UserId");

                    b.ToTable("TareaTrace");
                });

            modelBuilder.Entity("Entities.Entities.Usuario", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("WebRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.HasIndex("WebRoleId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Entities.Entities.WebRole", b =>
                {
                    b.Property<Guid>("WebRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WebRoleId");

                    b.ToTable("WebRoles");
                });

            modelBuilder.Entity("Entities.Entities.MiembroProyecto", b =>
                {
                    b.HasOne("Entities.Entities.Proyecto", "Proyecto")
                        .WithMany("Miembros")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Usuario", "Usuario")
                        .WithMany("ProyectosAsignados")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entities.Tarea", b =>
                {
                    b.HasOne("Entities.Entities.Proyecto", "Proyecto")
                        .WithMany("Tareas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Entities.Entities.TareaColaborador", b =>
                {
                    b.HasOne("Entities.Entities.Tarea", "Tarea")
                        .WithMany("Colaboradores")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Usuario", "Usuario")
                        .WithMany("TareasComoColaborador")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entities.TareaSolicitudBaja", b =>
                {
                    b.HasOne("Entities.Entities.Tarea", "Tarea")
                        .WithMany("SolicitudesBaja")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Usuario", "Usuario")
                        .WithMany("SolicitudesBaja")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entities.TareaTrace", b =>
                {
                    b.HasOne("Entities.Entities.Tarea", "Tarea")
                        .WithMany("TareasTrace")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Entities.Usuario", "Usuario")
                        .WithMany("TareasTrace")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Entities.Entities.Usuario", b =>
                {
                    b.HasOne("Entities.Entities.WebRole", "WebRole")
                        .WithMany("Usuarios")
                        .HasForeignKey("WebRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebRole");
                });

            modelBuilder.Entity("Entities.Entities.Proyecto", b =>
                {
                    b.Navigation("Miembros");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("Entities.Entities.Tarea", b =>
                {
                    b.Navigation("Colaboradores");

                    b.Navigation("SolicitudesBaja");

                    b.Navigation("TareasTrace");
                });

            modelBuilder.Entity("Entities.Entities.Usuario", b =>
                {
                    b.Navigation("ProyectosAsignados");

                    b.Navigation("SolicitudesBaja");

                    b.Navigation("TareasComoColaborador");

                    b.Navigation("TareasTrace");
                });

            modelBuilder.Entity("Entities.Entities.WebRole", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
